name: .NET 8 Build, Test, and Package with MongoDB

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Run Build, Test, and Package via Python Script
      run: python script.py